-- ADVANCED SQL ANALYSIS QUERIES
-- End-to-End PostgreSQL Data Analyst Project

-- 1. Retrieve customer names with their total number of orders
SELECT 
    c.Name AS Customer_Name,
    COUNT(o.Order_ID) AS Total_Orders
FROM Customers c
JOIN Orders o ON c.Customer_ID = o.Customer_ID
GROUP BY c.Name
ORDER BY Total_Orders DESC;

-- 2. Calculate total revenue generated by each book
SELECT 
    b.Title,
    SUM(o.Total_Amount) AS Total_Revenue
FROM Books b
JOIN Orders o ON b.Book_ID = o.Book_ID
GROUP BY b.Title
ORDER BY Total_Revenue DESC;

-- 3. Find the top 5 best-selling books by quantity
SELECT 
    b.Title,
    SUM(o.Quantity) AS Total_Quantity_Sold
FROM Books b
JOIN Orders o ON b.Book_ID = o.Book_ID
GROUP BY b.Title
ORDER BY Total_Quantity_Sold DESC
LIMIT 5;

-- 4. Identify customers who spent more than $50
SELECT 
    c.Name,
    SUM(o.Total_Amount) AS Total_Spent
FROM Customers c
JOIN Orders o ON c.Customer_ID = o.Customer_ID
GROUP BY c.Name
HAVING SUM(o.Total_Amount) > 50
ORDER BY Total_Spent DESC;

-- 5. Find average book price by genre
SELECT 
    Genre,
    AVG(Price) AS Avg_Book_Price
FROM Books
GROUP BY Genre
ORDER BY Avg_Book_Price DESC;

-- 6. Find monthly sales revenue
SELECT 
    DATE_TRUNC('month', Order_Date) AS Month,
    SUM(Total_Amount) AS Monthly_Revenue
FROM Orders
GROUP BY Month
ORDER BY Month;

-- 7. Identify books that have never been ordered
SELECT 
    b.Title
FROM Books b
LEFT JOIN Orders o ON b.Book_ID = o.Book_ID
WHERE o.Order_ID IS NULL;

-- 8. Find customers who placed more than 1 order
SELECT 
    c.Name,
    COUNT(o.Order_ID) AS Orders_Count
FROM Customers c
JOIN Orders o ON c.Customer_ID = o.Customer_ID
GROUP BY c.Name
HAVING COUNT(o.Order_ID) > 1;

-- 9. Calculate revenue contribution percentage by each genre
SELECT 
    b.Genre,
    ROUND(SUM(o.Total_Amount) * 100.0 / 
        (SELECT SUM(Total_Amount) FROM Orders), 2) AS Revenue_Percentage
FROM Books b
JOIN Orders o ON b.Book_ID = o.Book_ID
GROUP BY b.Genre
ORDER BY Revenue_Percentage DESC;

-- 10. Rank books based on total revenue
SELECT 
    b.Title,
    SUM(o.Total_Amount) AS Revenue,
    RANK() OVER (ORDER BY SUM(o.Total_Amount) DESC) AS Revenue_Rank
FROM Books b
JOIN Orders o ON b.Book_ID = o.Book_ID
GROUP BY b.Title;
